export const types = Object.freeze({
    // Sync
    COMMENTS_START_FETCHING: 'COMMENTS_START_FETCHING',
    COMMENTS_STOP_FETCHING: 'COMMENTS_STOP_FETCHING',
    COMMENTS_FILL: 'COMMENTS_FILL',
    COMMENTS_SET_FETCHING_ERROR: 'COMMENTS_SET_FETCHING_ERROR',
    // Async
    COMMENTS_FETCH_ASYNC: 'COMMENTS_FETCH_ASYNC',
});