export const types = Object.freeze({
    // Sync
    SIMILAR_FILMS_START_FETCHING: 'SIMILAR_FILMS_START_FETCHING',
    SIMILAR_FILMS_STOP_FETCHING: 'SIMILAR_FILMS_STOP_FETCHING',
    SIMILAR_FILMS_SET_FETCHING_ERROR: 'SIMILAR_FILMS_SET_FETCHING_ERROR',

    SIMILAR_FILMS_FILL: 'SIMILAR_FILMS_FILL',

    // Async
    SIMILAR_FILMS_FETCH_ASYNC: 'SIMILAR_FILMS_FETCH_ASYNC'
});
