export const types = Object.freeze({
    // Sync
    FILM_DETAILS_START_FETCHING: 'FILM_DETAILS_START_FETCHING',
    FILM_DETAILS_STOP_FETCHING: 'FILM_DETAILS_STOP_FETCHING',
    FILM_DETAILS_FILL: 'FILM_DETAILS_FILL',
    FILM_DETAILS_SET_FETCHING_ERROR: 'FILM_DETAILS_SET_FETCHING_ERROR',
    // Async
    FILM_DETAILS_FETCH_ASYNC: 'FILM_DETAILS_FETCH_ASYNC',
});