export const types = Object.freeze({
    RECOMMENDED_MOVIES_START_FETCHING: 'RECOMMENDED_MOVIES_START_FETCHING',
    RECOMMENDED_MOVIES_STOP_FETCHING: 'RECOMMENDED_MOVIES_STOP_FETCHING',
    RECOMMENDED_MOVIES_FILL: 'RECOMMENDED_MOVIES_FILL',
    RECOMMENDED_MOVIES_SET_FETCHING_ERROR: 'RECOMMENDED_MOVIES_SET_FETCHING_ERROR',
    RECOMMENDED_MOVIES_FETCH_ASYNC: 'RECOMMENDED_MOVIES_FETCH_ASYNC',
});