export const types = Object.freeze({
    TOP_RATED_FILMS_START_FETCHING: 'TOP_RATED_FILMS_START_FETCHING',
    TOP_RATED_FILMS_STOP_FETCHING: 'TOP_RATED_FILMS_STOP_FETCHING',
    TOP_RATED_FILMS_FILL: 'TOP_RATED_FILMS_FILL',
    TOP_RATED_FILMS_SET_FETCHING_ERROR: 'TOP_RATED_FILMS_SET_FETCHING_ERROR',
    TOP_RATED_FILMS_FETCH_ASYNC: 'TOP_RATED_FILMS_FETCH_ASYNC',
});
