export const types = Object.freeze({
    // Sync
    POPULAR_FILMS_START_FETCHING: 'POPULAR_FILMS_START_FETCHING',
    POPULAR_FILMS_STOP_FETCHING: 'POPULAR_FILMS_STOP_FETCHING',
    POPULAR_FILMS_FILL: 'POPULAR_FILMS_FILL',
    POPULAR_FILMS_SET_FETCHING_ERROR: 'POPULAR_FILMS_SET_FETCHING_ERROR',
    // Async
    POPULAR_FILMS_FETCH_ASYNC: 'POPULAR_FILMS_FETCH_ASYNC',
});