export const types = Object.freeze({
    // Sync
    LATEST_FILMS_START_FETCHING: 'LATEST_FILMS_START_FETCHING',
    LATEST_FILMS_STOP_FETCHING: 'LATEST_FILMS_STOP_FETCHING',
    LATEST_FILMS_SET_FETCHING_ERROR: 'LATEST_FILMS_SET_FETCHING_ERROR',

    LATEST_FILMS_FILL: 'LATEST_FILMS_FILL',

    // Async
    LATEST_FILMS_FETCH_ASYNC: 'LATEST_FILMS_FETCH_ASYNC'
});
