export const types = Object.freeze({
    TRENDING_MOVIES_START_FETCHING: 'TRENDING_MOVIES_START_FETCHING',
    TRENDING_MOVIES_STOP_FETCHING: 'TRENDING_MOVIES_STOP_FETCHING',
    TRENDING_MOVIES_FILL: 'TRENDING_MOVIES_FILL',
    TRENDING_MOVIES_SET_FETCHING_ERROR: 'TRENDING_MOVIES_SET_FETCHING_ERROR',
    TRENDING_MOVIES_FETCH_ASYNC: 'TRENDING_MOVIES_FETCH_ASYNC',
});
